### PR TITLE
Add Resource Buffer into Watermark structure

### PR DESCRIPTION
**Pull request by kben**
With a resouce buffer it is possible to add watermarks saved in a
different location than the filesystem. Just to create the watermark
resource and afterwards add the content to the ResourceBuffer member.

### CODE REVIEW

**Comment by hhrutter** [comment]
Hello, I am unable to accept this unless you sign the CLA.

**Comment by kben** [comment]
Hi, do you still need more information from my site to do the merge?

**Comment by hhrutter** [comment]
I am working on preparing a release over the next couple of days and this will be part of it.

**Comment by hhrutter** [comment]
This is resolved with v0.3.12.
Thank you for contribution.

**Pull request closed without merging**
