### PR TITLE
Fix GOPATH install instructions

### PR DESCRIPTION
**Pull request by dflock**

### CODE REVIEW

**Comment by hhrutter** [comment]
Hi there!

Please state your OS and go version.
`go get github.com/pdfcpu/pdfcpu/cmd/...` should still work with `GO111MODULE=off` as of go 1.15.

FYI support for GOPATH mode will be dropped in Go 1.17 and pdfcpu will soon require at least Go 1.16
which means the install instruction will also be updated.

Thanks for using pdfcpu 💚

**Comment by dflock** [comment]
```console
$ go version

go version go1.15.7 linux/amd64

$ cat /etc/os-release 

NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"

$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/duncan/.cache/go-build"
GOENV="/home/duncan/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/duncan/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/duncan/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build851545778=/tmp/go-build -gno-record-gcc-switches"

```

**Comment by hhrutter** [comment]
`GO111MODULE=""` might be the reason why the original GOPATH based install instructions didn't work for you but I am unsure about this.

**Comment by dflock** [comment]
I have no idea. I'm not setting `GO111MODULE` anywhere, go is doing it, but I have no idea what it does, sorry!

**Comment by hhrutter** [comment]
Fair enough, like I said once we are on 1.17 GOPATH will be gone.

**Pull request closed without merging**
