### PR TITLE
Radio Group Options and Encoding

### LINKED ISSUE #940: Radio Button Groups. Missmatched options, text render issues
Ubuntu 22.04.4 LTS
pdfcpu v0.8.1 dev

The Following File: 
[test.pdf](https://github.com/user-attachments/files/16844977/test.pdf)

produces this output when getting all form fields: (./pdfcpu form list test.pdf)
     RadioBGr. │ 1121 │ rbtn_23_Betriebsgroesse                                           │ 0,1,2,3
     Textfield │ 1181 │ txtf_24_Bezeichnung_Maßnahme                                      │ 
     Textfield │ 1179 │ txtf_25_Lehrgangskosten                                           │ 
     RadioBGr. │ 1175 │ rbtn_26_Betriebsvereinbarung                                      │ 0,1
     RadioBGr. │ 1169 │ rbtn_27_Betriebsvereinbarung                                      │ 0,1
━━━━━━━━━━━━━━━┿━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━
3    Textfield │ 1081 │ txtf_28_Anzahl_Beschaeftigte                                      │ 
     Textfield │ 1079 │ txtf_29_Berufliche_Kompetenzen                                    │ 
     Textfield │ 1077 │ txtf_30_Erlaeuterung_Aufgaben                                     │ 
     RadioBGr. │ 1073 │ rbtn_31_Massnahmen                                                │ 0,1
     RadioBGr. │ 1067 │ rbtn_32_Dauer_Massnahmen                                          │ 0,1
     RadioBGr. │ 1061 │ rbtn_33_Inhalte_Massnahmen                                        │ 0,1
     RadioBGr. │ 1055 │ rbtn_34_Kostenpauschale                                           │ 0,1
     RadioBGr. │ 1049 │ rbtn_35_Beschaeftigungsverhaeltnisse_sozialversicherungspflichtig │ 0,1
━━━━━━━━━━━━━━━┿━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━
4    RadioBGr. │ 878  │ rbtn_36_Massnahme_in_Arbeitszeiten                                │ 0,1
     RadioBGr. │ 854  │ rbtn_39_Kurzarbeitergeld_beantragt                                │ 0,1
     Textfield │ 941  │ txtf_40_Name_Zeile1                                               │ 
...
     Textfield │ 861  │ txtf_38_Zuschuss                                                  │ 
━━━━━━━━━━━━━━━┿━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━
5    Textfield │ 786  │ txtf_41_Ort                                                       │ 
     Textfield │ 784  │ txtf_42_Datum                                                     │ 
     Textfield │ 782  │ txtf_43_Name                                                      │ 
     RadioBGr. │ 775  │ chbx_Anlage_Tabelle_1_Z1                                          │ beigef�gt,wird nachgereicht,bereits vorliegend,entfaellt
     RadioBGr. │ 766  │ chbx_Anlage_Tabelle_1_Z2                                          │ beigef�gt,wird nachgereicht,bereits vorliegend,entfaellt
     RadioBGr. │ 757  │ chbx_Anlage_Tabelle_1_Z3                                          │ beigefuegt,wird nachgereicht,bereits vorliegend,entfaellt
     RadioBGr. │ 748  │ chbx_Anlage_Tabelle_1_Z4                                          │ beigefuegt,wird nachgereicht,bereits vorliegend,entfaellt
     RadioBGr. │ 739  │ chbx_Anlage_Tabelle_1_Z5                                          │ beigefuegt,wird nachgereicht,bereits vorliegend,entfaellt
     RadioBGr. │ 730  │ chbx_Anlage_Tabelle_1_Z6                                          │ beigefuegt,wird nachgereicht,bereits vorliegend,entfaellt
     RadioBGr. │ 721  │ chbx_Anlage_Tabelle_1_Z7                                          │ beigefuegt,wird nachgereicht,bereits vorliegend,entfaellt
     Textfield │ 717  │ Sonstige_Anlagen_Zeile_2                                          │ 

First Problem here, field rbtn_26_Betriebsvereinbarung has in a PDF Editor the options "Ja" and "Nein". 
Seems like there being wrongly read?

Also filling the form is somehow a problem. I'm not sure wheter it is the PDF File or just a bug, but what happens when you fill the form now.

used test fields:
mapping := map[string]interface{}{
		"txtf_Tag_Antragstellung":      "test",
		"rbtn_26_Betriebsvereinbarung": "0",
		"rbtn_27_Betriebsvereinbarung": "1",
}

with defautlt config and NeedAppearances = true.
Form Text fields are filled, but when the PDF File is opened with an older PDF Client or Adobe Acrobat Reader the Radio Groups are no longer filled. Also in Firefox ESR 115.14.0esr (pdfjs 3.7.96 it looks scrambled.

with defautlt config and NeedAppearances = false.
every PDF Editor is showing the Radio Groups selection correctly. But the text is scrampled in every PDF Viewer.

I tried at least for a day to find a working solution to use the original file as input without changing it too much, but didn't got far. Seems like this PDF File is kinda special. I also tried to change other settings in pdfcpu but also didn't helped here. 
Thanks.

### PR DESCRIPTION
**Pull request by LNAhri**
Should fix #940.

Needs more prober testing, In my case I didn't found any issues why the pdfs I found.

### CODE REVIEW

**Comment by hhrutter** [comment]
I'll check it out..

**Comment by hhrutter** [comment]
This is not supposed to fix the problem that filled textfield appearance streams are using the wrong font dict with this very file - correct?

**Comment by hhrutter** [comment]
I am afraid this is a much bigger change.
We need to support optional **Opt** entries for all button and choice fields.
In addition all form sub commands need to be able to handle this extension.
This all is fixed with the latest commit resolving #940 completely including fixing broken appearance streams for text fields.

See additional notes at #940

Thank for discovering all this though and digging into it 💚

**Comment by LNAhri** [comment]
Hey many thanks for the fix for the rest of the issue. Was still figuring out the other stuff ^^. 💚
But i have one more question. I changed this line in form/fill.go:
from 
	s := types.EncodeName(vNew)
	v := types.Name(s)
	d["V"] = v
to
	s, err := types.Escape(vNew)
	if err != nil {
		return err
	}
	v := types.Name(*s)
	d["V"] = v

because the original Thing would result in the setted value: 500#20und#20mehr#20Beschaeftigte
and this is something the PDF Viewers don't like as a value.

**Comment by hhrutter** [comment]
The PDF spec defines a proper encoding for names.
Which viewer is giving you this problem.
I checked with Adobe and Mac Preview - all looking good,

**Pull request closed without merging**
