### PR TITLE
Watermark remove white objects

### PR DESCRIPTION
**Pull request by mipmip**
To make watermark visiable on non-transparent document i have a method to remove all white rectangles.

I've have working example removing substrings of the content stream. Everything between "/Cs1 cs 1 1 1 sc" and "/Cs1 cs 0 0 0 sc" and everything between "1 1 1 rg", "0 0 0 rg" is removed.

This might be a little simplistic, but I it used to work quiet fine in a Mac app I made. I wonder if this could be part of pdfcpu or if you have comments on this.

### CODE REVIEW

**Comment by hhrutter** [comment]
Hi, thanks for your contribution.

Could you maybe share an example, I don't fully understand the issue here.

Stamps get drawn as the last content whereas watermarks get drawn first.
If a watermark or some part of it is hidden in general my recommendation is to use a stamp with some opaqueness.
That usually serves the purpose.

**Comment by hhrutter** [comment]
In general I think patching content streams like you are suggesting is smth too invasive for pdfcpu.

**Comment by mipmip** [comment]
Here are two pdf which can be used to test this feature.

[watermark.pdf](https://github.com/pdfcpu/pdfcpu/files/6732182/achtergrond.pdf)
[letter-non-transparent.pdf](https://github.com/pdfcpu/pdfcpu/files/6732187/tekstdocument.pdf)

The letter was made with Apple Pages.

I run  ```./pdfcpu watermark add -m pdf -- "achtergrond.pdf" "rot:0, scale:1.0 rel" tekstdocument.pdf out1.pdf```

**Comment by hhrutter** [comment]
Sorry - I don't feel confident making this kind of content stream manipulation part of pdfcpu.

**Pull request closed without merging**
