### PR TITLE
WIP: Feat PDF Redaction

### PR DESCRIPTION
**Pull request by httpsOmkar**
I am interested in adding feature of redaction in this library.

[Referance](https://helpx.adobe.com/acrobat/using/removing-sensitive-content-pdfs.html)

### CODE REVIEW

**Comment by httpsOmkar** [comment]
I found out that it is already there

**Comment by hhrutter** [comment]
Hey, thanks for using pdfcpu!

I appreciate all your suggestions but most of them degrade code readability.
However, I gladly accept the fixes for attach.go and types.go.
If you get rid of the other changes and push a [signed commit](https://help.github.com/en/github/authenticating-to-github/signing-commits) I am happy to merge in.
💚

**Comment by hhrutter** [comment]
>>I am interested in adding feature of redaction in this library.
Please open a separate issue for this feature request.
Thank you!

**Comment by hhrutter** [comment]
Hello!

Are you planning on resubmitting?
If not I am going to close this.

**Comment by httpsOmkar** [comment]
Yes I was busy in the some stuff. I got free on that will continue on this.

**Pull request closed without merging**
