### PR TITLE
Allow for verbose parameters

### PR DESCRIPTION
**Pull request by signalwerk**
I think a command like `al:j` works great if you are very familiar with the command. But if you wanna have others on board you probably use `aligntext: j`. But it might be greate if you can also use `aligntext: justify`. I addes some more alternatives

### CODE REVIEW

**Comment by hhrutter** [comment]
Thank you for your contribution.
Please do me a favour and update the usage accordingly.

**Comment by signalwerk** [comment]
@hhrutter sorry I'm not sure what you are referencing. Usage of what?

**Comment by hhrutter** [comment]
All cli commands are documented as well at the command line. 
See [usage.go](https://github.com/pdfcpu/pdfcpu/blob/master/cmd/pdfcpu/usage.go):
```
Go-> pdfcpu import
usage: pdfcpu import -- [description] outFile imageFile...

common flags: -v(erbose)  ... turn on logging
              -vv         ... verbose logging
              -q(uiet)    ... disable output
              -c(onf)     ... set or disable config dir: $path|disable
              -opw        ... owner password
              -upw        ... user password
              -u(nit)     ... display unit: po(ints) ... points
                                            in(ches) ... inches
                                                  cm ... centimetres
                                                  mm ... millimetres

Go-> pdfcpu help import
usage: pdfcpu import -- [description] outFile imageFile...

common flags: -v(erbose)  ... turn on logging
              -vv         ... verbose logging
              -q(uiet)    ... disable output
              -c(onf)     ... set or disable config dir: $path|disable
              -opw        ... owner password
              -upw        ... user password
              -u(nit)     ... display unit: po(ints) ... points
                                            in(ches) ... inches
                                                  cm ... centimetres
                                                  mm ... millimetres

Turn image files into a PDF page sequence and write the result to outFile.
If outFile already exists the page sequence will be appended.
Each imageFile will be rendered to a separate page.
In its simplest form this converts an image into a PDF: "pdfcpu import img.pdf img.jpg"

description ... dimensions, format, position, offset, scale factor, boxes
    outFile ... output pdf file
  imageFile ... a list of image files

  <description> is a comma separated configuration string containing:

  optional entries:

      (defaults: "d:595 842, f:A4, pos:full, off:0 0, sc:0.5 rel, dpi:72, gray:off, sepia:off")

  dimensions:      (width height) in given display unit eg. '400 200' setting the media box
  formsize:        eg. A4, Letter, Legal...
                   Append 'L' to enforce landscape mode. (eg. A3L)
                   Append 'P' to enforce portrait mode. (eg. TabloidP)
                   Please refer to "pdfcpu paper" for a comprehensive list of defined paper sizes.
                   "papersize" is also accepted.
  position:        one of 'full' or the anchors: tl,tc,tr, l,c,r, bl,bc,br
  offset:          (dx dy) in given display unit eg. '15 20'
  scalefactor:     0.0 <= x <= 1.0 followed by optional 'abs|rel' or 'a|r'
  dpi:             apply desired dpi
  gray:            Convert to grayscale (on/off, true/false, t/f)
  sepia:           Apply sepia effect (on/off, true/false, t/f)
  backgroundcolor: "bgcolor" is also accepted.

  Only one of dimensions or format is allowed.
  position: full => image dimensions equal page dimensions.

  All configuration string parameters support completion.

  e.g. "f:A5, pos:c"                              ... render the image centered on A5 with relative scaling 0.5.'
       "d:300 600, pos:bl, off:20 20, sc:1.0 abs" ... render the image anchored to bottom left corner with offset 20,20 and abs. scaling 1.0.
       "pos:full"                                 ... render the image to a page with corresponding dimensions.
       "f:A4, pos:c, dpi:300"                     ... render the image centered on A4 respecting a destination resolution of 300 dpi.

```

**Comment by signalwerk** [comment]
@hhrutter Thank you for explaining. I just updated the usage file. It is now in sync with the doc and keeps the same formatting for all parameters.


((please keep in mind I just edited the file – I never compiled the files, but I hope I din't break stuff))

**Comment by hhrutter** [comment]
I had to correct your version of usage.
Some parts were missing, other changes were not discussed.
Reflected changes correspond to modifications for stamping and importing only.
Thank you for your contribution!

**Pull request merged**
