### PR TITLE
Booklet ordering - public method

### PR DESCRIPTION
**Pull request by adamgreenhall**
https://github.com/pdfcpu/pdfcpu/issues/816

I want to use the booklet ordering (currently internal to pdfcpu) somewhere else in my code.

to do this, I rearranged the `multifolio` code and added some test cases

I also tweaked the cli description of `multifolio` - I'm much more familiar calling this concept "signatures"

### CODE REVIEW

**Comment by hhrutter** [comment]
Hello!
I am about to cut a release so there is a code freeze in effect as far as PRs.
I need to get back to you about this in order to gain a better understanding about the purpose of this PR.
Talk to you later!

**Comment by adamgreenhall** [comment]
sounds good. no rush.

**Comment by hhrutter** [comment]
Hi Adam, 
Do we also need to merge the generated PDF files which are part of this?
Have they changed?

**Comment by adamgreenhall** [comment]
They have not changed - just run tests and committed results to confirm.

**Comment by hhrutter** [comment]
ok then, I am gonna leave them out to avoid unnecessary repo size bloat.

**Comment by hhrutter** [comment]
This is merged in !

**Pull request closed without merging**
