### PR TITLE
Fix building from distribution archive

### PR DESCRIPTION
**Pull request by afh**
For details please see #751

### CODE REVIEW

**Comment by afh** [comment]
@hhrutter I thought a bit more about this PR and think that the latest proposed changes here are much less disruptive to pdfcpu's `version` output, while avoiding a panic, if `commit` does not contain expected data, thus allowing distributions to provide commit info from the outside instead of a git repo.

**Comment by hhrutter** [comment]
😞 This way pdfcpu loses control about the `version` output.
My stance is, if debug.ReadInfo is not available then the build has failed - this approach does not serve this intention.

The output of `pdfcpu.version` for a particular version is set in stone and must be identical no matter the platform.

The options are you build straight from the repo or grab the binary from Github.
You do this once for every release, so maybe 4 or 5 times a year..
I wonder how other Linux distros deal with this.

**Comment by afh** [comment]
I see your point and respect your stance, @hhrutter, and am trying to find the best compromise between pdfcpu's and nixpkgs (potentially somewhat contradicting) preferences and requirements.

Note that I'm an interested user and keen learner of Nixpkgs and NixOS, but by no means (yet?) deeply involved in the project, so my knowledge is limited and from that my assumptions could be wrong. If my statements are incorrect, I'm happy to be corrected 🙂 

Nixpkgs is a source based distribution and strives for [reproducible builds](https://reproducible.nixos.org), so grabbing the binary from GitHub does not serve that purpose.
While pre-build binaries are available for NixOS and Nixpkgs from my experience Nix builds software more often than not (especially with [Nix Flakes](https://nixos.wiki/wiki/Flakes)), so pdfcpu's Git repository would likely be downloaded from many, many more users than just the Nix organisation and much, much more frequently than 4 or 5 times a year.

I've proposed a few options (see [my comment on NixOS/nixpkgs#273438](https://github.com/NixOS/nixpkgs/pull/273438#discussion_r1424981192)), let's see where this leads to.

**Comment by afh** [comment]
I'll keep an eye out for pdfcpu 0.6.0 on other distributions, if you know of any that have already updated, please let me know.

**Comment by afh** [comment]
Thank you for providing additional details on Nix, @doronbehar, very much appreciated. If I wanted to read more on the topic where should I start?

@hhrutter I'll leave this PR open as I believe it improves the code by avoiding a panic, even at the cost that the commit may not show the intended/desired information.
Please merge or discard it as you see fit 🙂 

As for the pdfcpu update to 0.6.0 in Nixpkgs, it is build from the git source and the `version` command will show the commit and date values from the git clone.

**Pull request merged**
