### PR TITLE
Fix JS build

### PR DESCRIPTION
**Pull request by scoiatael**
Hey,

looks like WASM version stopped building some time ago.

```
$ env GOOS=js GOARCH=wasm go build
# github.com/pdfcpu/pdfcpu/pkg/pdfcpu
../../pkg/pdfcpu/parseConfig_js.go:219:28: too many arguments in call to handleHeaderBufSize
        have (string, string, *Configuration)
        want (string, *Configuration)
```

This fixes the problem. Maybe WASM build should be added to GH actions since it has some build-specific files?

### CODE REVIEW

**Comment by hhrutter** [comment]
Thanks for discovering this.
A separate Github action does make sense.

**Comment by hhrutter** [comment]
If you can add it that would be nice.
There is already an OS matrix in test.yml and this does not fit in.
I guess we need another workflow then triggered by push, pull_request.

**Comment by scoiatael** [comment]
Done - new workflow should cross-compile from Linux to a couple of standard targets. Looks like it needs approval before it can run, so kinda hard to verify if it works by myself.

**Comment by hhrutter** [comment]
Thanks, this will go live together with the upcoming release.

**Comment by hhrutter** [comment]
Fixed as of v0.4.0

**Comment by scoiatael** [comment]
> Fixed as of v0.4.0

Looks like it was closed, but not merged? I see that the original issue seems to be fixed in 0.4.0, but the Github workflow is not there.

**Comment by hhrutter** [comment]
Your contribution was integrated into the main workflow.
Had a lot of headache going on with refactoring..
Hope that's ok with you.
🙏 Thank you!

**Pull request closed without merging**
