### PR TITLE
fix buffer handling

### PR DESCRIPTION
**Pull request by HeavyHorst**
The code assumed that all read operations (io.Reader) are filling the given buffer completely until EOF is reached.
This is not the case with all io.Readers.

I added a helper function fillBuffer that reads from the reader until the buffer is full or EOF is reached.
Unlike io.ReadFull this function doesn't return ErrUnexpectedEOF if an EOF happens before the buffer is filled.
It behaves as a normal io.Read call but reads until the buffer is full.

### CODE REVIEW

**Comment by HeavyHorst** [comment]
Hallo auch!

I've added a test to demonstrate the issue.
Without this PR I get this error:
//read_test.go:52: couldn't create pdf context:  Read: xRefTable failed: pdfcpu: can't find last xref section

**Comment by hhrutter** [comment]
What I need to see is the usecase / PDF that demonstrates and reproduces the issue you'd like to address with this.

**Comment by HeavyHorst** [comment]
My usecase: i have an http.Filesystem that serves Files directly from ZIP Files. I Split the Files into Pages/chunks of 4MB each to Support seeking (for example in Videos). Without chunkig you have to reread everything from the beginning of the io.reader.

When the Buffer ist bigger then the current Page i read till the end of the page and Return the Bytes read. This is conform to the io.Reader Interface and should Work.

I'll try to construct a better example.

**Comment by HeavyHorst** [comment]
From the Io.Reader documentation: 

Read reads up to len(p) bytes into p. It returns the number of bytes read (0 <= n <= len(p)) and any error encountered. Even if Read returns n < len(p), it may use all of p as scratch space during the call. If some data is available but not len(p) bytes, Read conventionally returns what is available instead of waiting for more.

So some totally fine Reader Implementations arent working at the moment. This PR fixes this.

**Comment by hhrutter** [comment]
This may be a dumb question but where is the PDF usecase here?

**Comment by HeavyHorst** [comment]
I have an http handler that returns the page Labels for a given PDF. The handler has Access to the http Filesystem. I wasnt able to give the http.file to pdfcpu directly because of this issue. Reading the whole File into a Byte Buffer worked but i searched for the underlying issue and thought i fix it.

**Comment by hhrutter** [comment]
I need to know more about this..
Can we continue on the #pdfcpu Slack channel?

**Comment by hhrutter** [comment]
I think I understand your usecase.

In my opinion the filling of the read buffer is the responsibility of the reader.

If you fill up the chunked read buffer in your reader (or one of your stacked readers)
like so then we don't have to change anything in read.go:

```
type smallbufferreader struct {
	rs io.ReadSeeker
}

func (sm *smallbufferreader) ReadChunk(p []byte, size int) (int, error) {
	b := make([]byte, size)
	n, err := sm.rs.Read(b)
	copy(p, b)
	return n, err
}

// Read reads up to chunkSize bytes into p. It returns the number of bytes read (0 <= n <= chunkSize) and any error encountered.
func (sm *smallbufferreader) Read(p []byte) (int, error) {
	chunkSize := 10
	var n int
	var err error

	for n < len(p) && err == nil {
		var nn int
		want := chunkSize
		if len(p)-n < chunkSize {
			want = len(p) - n
		}
		nn, err = sm.ReadChunk(p[n:], want)
		n += nn
	}

	return n, err
}

func (sm *smallbufferreader) Seek(offset int64, whence int) (int64, error) {
	return sm.rs.Seek(offset, whence)
}
```

**Pull request closed without merging**
